#! /bin/sh

setxkbmap gb

# Remap caps lock to escape
setxkbmap -option caps:escape

[ -f ".config/bspwm/screen.sh" ] && .config/bspwm/screen.sh

nitrogen --restore

killall -q sxhkd picom
sxhkd &
picom --experimental-backends &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

